/*:
 * @target MZ
 * @plugindesc 游戏内模组管理器
 * @author joker创意 & GLM核心代码 & Gemini修复滚轮bug
 *
 * @param Mod Button X
 * @type number
 * @default 20
 * @desc 模组管理按钮距离屏幕左侧的 X 坐标
 *
 * @param Mod Button Y
 * @type number
 * @default 20
 * @desc 模组管理按钮距离屏幕顶部的 Y 坐标
 *
 * @help
 * 【使用说明】
 * 1. 点击左边界面按钮，开启关闭mod
 * 2. 开启后会注册on插件至plugins.js内，off则取消注册。
 * 3. F5重启后生效改动
 */
(() => {
    // ================= 1. 绝对安全的配置 =================
    let BUTTON_X = 20;
    const MOD_ASSETS_PATH = 'js/mods/img/';
    let BUTTON_Y = 20;

    // ================= 2. Node.js 模块（启动极早，安全） =================
    const fs = require('fs');
    const pathMod = require('path');
    const MODS_DIR = pathMod.join(process.cwd(), 'js', 'mods');
    const CONFIG_PATH = pathMod.join(MODS_DIR, 'mod_config.json');
    const PLUGINS_PATH = pathMod.join(process.cwd(), 'js', 'plugins.js');
    const MOD_SECRET_FLAG = "__isMod";

    // ================= 3. 纯逻辑工具函数（不依赖任何RMMZ类，安全） =================
    function ensureDir(dir) {
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    }

    function loadConfig() {
        if (!fs.existsSync(CONFIG_PATH)) return {};
        try { return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8')); } 
        catch (e) { return {}; }
    }

    function saveConfig(config) {
        ensureDir(MODS_DIR);
        try { fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2), 'utf-8'); } 
        catch (e) {}
    }

    function parseModInfo(filePath) {
        try {
            const content = fs.readFileSync(filePath, 'utf-8');
            const authorMatch = content.match(/@author\s+(.+?)[\r\n]/);
            const helpMatch = content.match(/@help[\r\n]+([\s\S]*?)(?=\*\/|$)/);
            return {
                author: authorMatch ? authorMatch[1].trim() : "未知作者",
                help: helpMatch ? helpMatch[1].trim() : "无帮助信息"
            };
        } catch (e) {
            return { author: "解析失败", help: "" };
        }
    }

    function scanMods() {
        ensureDir(MODS_DIR);
        const config = loadConfig();
        const mods = [];
        try {
            const files = fs.readdirSync(MODS_DIR).filter(file =>
                file.endsWith('.js') && file !== 'ModLoader.js'
            );
            files.forEach(file => {
                const filePath = pathMod.join(MODS_DIR, file);
                const modId = "../mods/" + pathMod.parse(file).name;
                const info = parseModInfo(filePath);
                const status = typeof config[modId] === 'boolean' ? config[modId] : false;
                mods.push({
                    id: modId,
                    fileName: file,
                    displayName: pathMod.parse(file).name,
                    status: status,
                    author: info.author,
                    help: info.help
                });
            });
        } catch (e) {}
        return mods;
    }

    function updatePluginsJs(mods) {
        try {
            let content = fs.readFileSync(PLUGINS_PATH, 'utf-8');
            const lines = content.split('\n');
            const originalPlugins = [];
            
            for (const line of lines) {
                const objMatch = line.match(/^\s*(\{.*\})\s*,?\s*$/);
                if (objMatch) {
                    try {
                        let obj = JSON.parse(objMatch[1]);
                        if (!obj.hasOwnProperty(MOD_SECRET_FLAG)) {
                            originalPlugins.push(obj);
                        }
                    } catch (jsonErr) {}
                }
            }
            
            const originalPluginsStr = originalPlugins.map(p => JSON.stringify(p));
            const enabledModsStr = mods.filter(mod => mod.status).map(mod => {
                let modObj = {
                    "name": mod.id,
                    "status": true,
                    "description": mod.description || "",
                    "parameters": {},
                    [MOD_SECRET_FLAG]: true
                };
                return JSON.stringify(modObj);
            });
            
            const allPluginsStr = [...originalPluginsStr, ...enabledModsStr];
            let newContent = '// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n';
            newContent += allPluginsStr.join(',\n');
            newContent += '\n]\n';
            fs.writeFileSync(PLUGINS_PATH, newContent, 'utf-8');
        } catch (e) {
            console.error("ModManager: plugins.js 写入失败", e);
        }
    }

    // ================= 4. 延迟定义 UI 类（核心解法，避开解析期报错） =================
    let Scene_ModManager_Class = null;

    function initModClasses() {
        if (Scene_ModManager_Class) return; // 只在第一次点击时执行一次

        class Window_ModList extends Window_Selectable {
            initialize(rect) {
                super.initialize(rect);
                this._data = [];
                this.refresh();
            }
            maxItems() { return this._data ? this._data.length : 0; }
            makeCommandList() { this._data = scanMods(); }
            drawItem(index) {
                const mod = this._data[index];
                if (mod) {
                    const rect = this.itemLineRect(index);
                    const statusWidth = 60;
                    this.changeTextColor(mod.status ? ColorManager.textColor(24) : ColorManager.textColor(20));
                    this.drawText(mod.status ? "ON" : "OFF", rect.x, rect.y, statusWidth);
                    this.resetTextColor();
                    this.drawText(mod.displayName, rect.x + statusWidth, rect.y, rect.width - statusWidth);
                }
            }
            refresh() { this.makeCommandList(); super.refresh(); }
            currentMod() { return this._data[this.index()] || null; }
        }

        class Window_ModDetail extends Window_Base {
            initialize(rect) {
                super.initialize(rect);
                this._mod = null;
                this._scrollY = 0;
                this._maxScrollY = 0;
            }
            setMod(mod) {
                if (this._mod !== mod) {
                    this._mod = mod;
                    this._scrollY = 0;
                    this.refresh();
                }
            }
            update() { super.update(); this.processWheel(); }
            processWheel() {
                if (this._maxScrollY > 0 && this.isCursorInWindow()) {
                    if (TouchInput.wheelY > 0) { this.scrollDown(60); }
                    else if (TouchInput.wheelY < 0) { this.scrollUp(60); }
                }
            }
            isCursorInWindow() {
                const x = TouchInput.x;
                const y = TouchInput.y;
                return x >= this.x && x < this.x + this.width && y >= this.y && y < this.y + this.height;
            }
            scrollDown(amount) { this._scrollY = Math.min(this._scrollY + amount, this._maxScrollY); this.refresh(); }
            scrollUp(amount) { this._scrollY = Math.max(this._scrollY - amount, 0); this.refresh(); }
            lineHeight() { return 28; }
            refresh() {
                this.contents.clear();
                if (!this._mod) return;
                this.contents.fontSize = 20;
                const lh = this.lineHeight();
                let drawY = -this._scrollY;
                const width = this.contentsWidth();
                
                this.changeTextColor(ColorManager.systemColor());
                this.drawText("作者:", 0, drawY, width);
                this.resetTextColor();
                drawY += lh;
                this.drawText(this._mod.author || "未知", 10, drawY, width);
                drawY += lh * 1.5;
                
                this.changeTextColor(ColorManager.systemColor());
                this.drawText("帮助说明:", 0, drawY, width);
                this.resetTextColor();
                drawY += lh;
                
                const textState = this.createTextState(this._mod.help || "", 0, drawY, width);
                this.processAllText(textState);
                const totalHeight = textState.y + textState.height;
                const contentEnd = totalHeight - (-this._scrollY);
                this._maxScrollY = Math.max(0, contentEnd - this.contentsHeight() + 20);
                this.drawScrollbar();
                this.contents.fontSize = $gameSystem.mainFontSize();
            }
            drawScrollbar() {
                if (this._maxScrollY > 0) {
                    const x = this.contentsWidth() - 6;
                    const h = this.contentsHeight();
                    const barH = Math.max(20, h * (h / (h + this._maxScrollY)));
                    const barY = (h - barH) * (this._scrollY / this._maxScrollY);
                    this.contents.fillRect(x, 0, 4, h, 'rgba(0,0,0,0.2)');
                    this.contents.fillRect(x, barY, 4, barH, 'rgba(255,255,255,0.5)');
                }
            }
        }

        class Scene_ModManager extends Scene_MenuBase {
            create() {
                super.create();
                const rectL = new Rectangle(0, 0, Graphics.boxWidth / 3, Graphics.boxHeight);
                this._listWindow = new Window_ModList(rectL);
                this._listWindow.setHandler('ok', this.onModToggle.bind(this));
                this._listWindow.setHandler('cancel', this.popScene.bind(this));
                this.addWindow(this._listWindow);

                const rectR = new Rectangle(Graphics.boxWidth / 3, 0, (Graphics.boxWidth * 2) / 3, Graphics.boxHeight);
                this._detailWindow = new Window_ModDetail(rectR);
                this.addWindow(this._detailWindow);

                this._listWindow.activate();
                this._listWindow.select(0);
            }
            update() {
                super.update();
                const current = this._listWindow.currentMod();
                if (this._detailWindow && current !== this._detailWindow._mod) {
                    this._detailWindow.setMod(current);
                }
            }
            onModToggle() {
                const mod = this._listWindow.currentMod();
                if (mod) {
                    mod.status = !mod.status;
                    const config = loadConfig();
                    config[mod.id] = mod.status;
                    saveConfig(config);
                    updatePluginsJs(this._listWindow._data);
                    this._listWindow.refresh();
                }
                this._listWindow.activate();
            }
        }

        Scene_ModManager_Class = Scene_ModManager; // 暴露给外部使用
    }

    // ================= 5. 寄生注入逻辑 =================
    let lastSceneName = "";

    // 赋予定时器一个 ID，以便在完成注入后自我销毁
    const parasiteTimer = setInterval(() => {
        if (typeof SceneManager !== 'undefined' && SceneManager._scene) {
            const currentName = SceneManager._scene.constructor.name;

            if (currentName !== lastSceneName) {
                lastSceneName = currentName;

                if (currentName === "Scene_Title") {
                    const sceneInstance = SceneManager._scene;

                    if (!sceneInstance._modManagerParasited) {
                        sceneInstance._modManagerParasited = true;

                        const btn = new Sprite();
                        btn.bitmap = ImageManager.loadBitmap(MOD_ASSETS_PATH, '模组管理', true);
                        btn.x = BUTTON_X;
                        btn.y = BUTTON_Y;

                        btn._onTrigger = () => {
                            if (TouchInput.x >= btn.x && TouchInput.x < btn.x + btn.bitmap.width &&
                                TouchInput.y >= btn.y && TouchInput.y < btn.y + btn.bitmap.height) {
                                if (sceneInstance.isActive() && !sceneInstance.isBusy()) {
                                    initModClasses(); // 关键：在点击瞬间才定义类，此时绝对安全
                                    SceneManager.push(Scene_ModManager_Class);
                                    SoundManager.playOk();
                                }
                            }
                        };

                        sceneInstance.addChild(btn);

                        const originalInstanceUpdate = sceneInstance.update;
                        sceneInstance.update = function() {
                            originalInstanceUpdate.call(this);

                            // 每帧强制将按钮拉到最顶层，免疫光束、天气等特效遮挡
                            if (this.children && this.children.contains(btn)) {
                                this.setChildIndex(btn, this.children.length - 1);
                            }

                            // 监听点击事件
                            if (TouchInput.isTriggered() && btn.bitmap && btn.bitmap.isReady()) {
                                btn._onTrigger();
                            }
                        };

                        // 抛光：任务完成，彻底清除定时器，释放性能，不留垃圾
                        // clearInterval(parasiteTimer);
                    }
                }
            }
        }
    }, 100);

})();
